### ISSUE TITLE
insertion condition for the queue

### ISSUE THREAD

**Issue by n4vn337** [farhank9821/Ds_lab#3]
code for line 62 should be
`    if (r == n-1)
`
because we are implementing it in an array, and index starts from 0. so the condition for the queue to be full should be n-1 (where n is the size of the queue as per the code)

let me know if this is wrong

**Comment by farhank9821** [comment]
Oh, good catch. Thanks for letting me know Navneet. I've updated it
________________________________
From: Navneet Anand ***@***.***>
Sent: 06 November 2022 18:14
To: farhank9821/Ds_lab ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [farhank9821/Ds_lab] insertion condition for the queue (Issue #3)


code for line 62 should be
if (r == n-1)
because we are implementing it in an array, and index starts from 0. so the condition for the queue to be full should be n-1 (where n is the size of the queue as per the code)

let me know if this is wrong
